export const Lang = {
  titleProject: 'Finso',
  somethingWentWrong: 'Something went wrong',
  ok: 'ok',
  topHeadlines: 'Top Headlines',
  news: 'News',
  userSettings: 'User Settings',
  noData: 'No data',
  register: 'Register',
  login: 'Login',
  iWantToLogin: 'I want to login',
  dontHaveAccount: "Don't have account",
  enterHere: 'Enter here',
  name: 'Your Name',
  username: 'User Name',
  password: 'Password',
  loginToChangeData: 'You need to login to change data',
  validateName: 'Your name should be anphabet',
  validateUserName: 'User name should be anphabet or number',
  validatePassword: 'Your password should not be blank',
  incorrect: 'Incorrect',
  registerSuccess: 'Register success',
  userNameisExisted: 'Username is existed',
  typeUserNameAndPassword: 'Please type username and password',
  incorrectUnserNameAndPassword: 'Username and password is incorrect',
  keywordNews: 'Keyword news',
  update: 'Update',
  saveSuccess: 'Save success',
  note: 'Note',
}
